// @generated-tool — embeds a built Vite `dist/` tree into a Rust source file as
// a static (path, bytes) table, so the soulrust binary can serve the SPA with
// no runtime filesystem dependency. Run hermetically as a Bazel js_run_binary
// (//crates/soulrust:web_assets); Node comes from the rules_js toolchain.
//
// Usage: node embed.mjs <dist-dir> <out-path>
// Both paths are relative to the js_run_binary working directory (BAZEL_BINDIR),
// so <dist-dir> is e.g. `frontend/dist` and <out-path> the declared `outs`
// entry, e.g. `crates/soulrust/src/web_assets_gen.rs`.
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { join, relative, dirname, sep } from "node:path";

const [distDir, outPath] = process.argv.slice(2);
if (!distDir || !outPath) {
  console.error("usage: embed.mjs <dist-dir> <out-path>");
  process.exit(1);
}

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

// A Rust byte-string literal: printable ASCII verbatim (bar " and \), the rest
// as \xNN. Valid for arbitrary bytes, and compiles far faster than a &[u8] of
// integer literals.
function toByteStringLiteral(buf) {
  let s = 'b"';
  for (const byte of buf) {
    if (byte === 0x22) s += '\\"';
    else if (byte === 0x5c) s += "\\\\";
    else if (byte >= 0x20 && byte <= 0x7e) s += String.fromCharCode(byte);
    else s += "\\x" + byte.toString(16).padStart(2, "0");
  }
  return s + '"';
}

const files = walk(distDir).sort();
let rs =
  "// @generated by //frontend:embed — do not edit.\n" +
  "// The Vite production bundle, embedded for the ApiServer to serve.\n" +
  "pub static WEB_ASSETS: &[(&str, &[u8])] = &[\n";
for (const file of files) {
  const rel = relative(distDir, file).split(sep).join("/");
  rs += `    (${JSON.stringify(rel)}, ${toByteStringLiteral(readFileSync(file))}),\n`;
}
rs += "];\n";

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, rs);
console.error(`embed: wrote ${files.length} asset(s) to ${outPath}`);
