//! Soulseek client built as nano-services on the rust-messenger bus.
//!
//! Components are synchronous `&mut self` handlers owned by worker threads;
//! they communicate only through bus messages (see [`messages`]). I/O lives
//! at the edges: [`components::api_server`] serves the Connect API + React UI
//! over axum, [`components::net_edge`] owns the Soulseek server socket.
//! Request/response across the bus uses correlation ids with reply channels
//! held by the API edge.
//!
//! The routing table — which component receives which message from which
//! source — lives in [`wiring`].

pub mod components;
pub mod config;
// The Vite React bundle, embedded as a `(path, bytes)` table and served by
// [`components::api_server`]. Generated by `//crates/soulrust:web_assets`
// (Bazel-only, like the proto codegen) — not present in a bare `cargo` tree.
mod web_assets_gen;
pub mod extract;
pub mod messages;
pub mod search_response;
pub mod shares;
pub mod transfers;
pub mod version;
pub mod wiring;
