use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rustc-check-cfg=cfg(cargo_build)");
    println!("cargo:rustc-cfg=cargo_build");

    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    fs::write(
        out.join("web_assets_gen.rs"),
        r#"// @generated by build.rs for Cargo builds.
pub static WEB_ASSETS: &[(&str, &[u8])] = &[];
"#,
    )
    .expect("write web_assets_gen.rs");
}
