//! Cross-implementation conformance: our codec vs Nicotine+'s real output.
//!
//! The byte vectors in `fixtures/nicotine_vectors.rs` are generated by running
//! Nicotine+'s own message packers (see scripts/gen-nicotine-vectors.py). These
//! tests assert that our encoder produces the same bytes Nicotine+ does, and
//! that our decoder accepts Nicotine+'s real SharedFileListResponse — making the
//! reference implementation the executed oracle, not a human reading of it.

use soulseek_proto::frame::split_frame;
use soulseek_proto::peer::{ConnectionType, PeerInit, PierceFirewall};
use soulseek_proto::peer_message::{
    FolderContentsRequest, GetSharedFileList, PeerMessage, UserInfoResponse,
};
use soulseek_proto::server::{
    FileSearchRequest, GetPeerAddressRequest, LoginRequest, ServerRequest, SetWaitPort,
};

mod vectors {
    include!("fixtures/nicotine_vectors.rs");
}

fn body<M: ServerRequest>(message: &M) -> Vec<u8> {
    let mut buf = Vec::new();
    message.encode_body(&mut buf);
    buf
}

#[test]
fn login_body_matches_nicotine() {
    let ours = body(&LoginRequest {
        username: "alice".into(),
        password: "s3cr3t".into(),
        major_version: 160,
        minor_version: 1,
    });
    // Includes the MD5(username+password) digest string — proves we compute it
    // the same way Nicotine+ does.
    assert_eq!(ours, vectors::LOGIN_BODY);
}

#[test]
fn get_peer_address_body_matches_nicotine() {
    let ours = body(&GetPeerAddressRequest { username: "alice".into() });
    assert_eq!(ours, vectors::GET_PEER_ADDRESS_BODY);
}

#[test]
fn file_search_body_matches_nicotine() {
    let ours = body(&FileSearchRequest { token: 0x1234_5678, query: "test query".into() });
    assert_eq!(ours, vectors::FILE_SEARCH_BODY);
}

#[test]
fn pierce_firewall_body_matches_nicotine() {
    // Peer-init frames are [u32 len][u8 code][body]; strip the 5-byte header.
    let frame = PierceFirewall { token: 4242 }.to_frame();
    assert_eq!(&frame[5..], vectors::PIERCE_FIREWALL_BODY);
}

#[test]
fn peer_init_body_matches_nicotine() {
    let frame = PeerInit {
        username: "alice".into(),
        connection_type: ConnectionType::Peer,
        token: 0,
    }
    .to_frame();
    assert_eq!(&frame[5..], vectors::PEER_INIT_BODY);
}

#[test]
fn shared_file_list_request_body_matches_nicotine() {
    // u32-code frames are [u32 len][u32 code][body]; the body is empty.
    let frame = GetSharedFileList.to_frame();
    assert_eq!(&frame[8..], vectors::SHARED_FILE_LIST_REQUEST_BODY);
}

#[test]
fn set_wait_port_is_a_soulseekqt_superset_of_nicotine() {
    // We send the SoulseekQt form: port + obfuscation_type + obfuscated_port.
    // Nicotine+ sends the port ALONE (slskmessages.py: `__slots__ = ("port",)`),
    // so the executed-oracle fixture SET_WAIT_PORT_BODY is just the 4-byte port.
    // The server accepts both; Nicotine+'s bytes must be the prefix of ours.
    let ours = body(&SetWaitPort { port: 2234, obfuscation_type: 0, obfuscated_port: 0 });
    assert_eq!(&ours[..vectors::SET_WAIT_PORT_BODY.len()], vectors::SET_WAIT_PORT_BODY);
    assert_eq!(ours.len(), 12, "port + obfuscation_type + obfuscated_port");
}

#[test]
fn our_decoder_accepts_nicotines_shared_file_list() {
    // Nicotine+'s real, compressed SharedFileListResponse with one public and
    // one private folder. Decoding it exercises the public dirs, the unknown=0
    // field, and the private-dir list — the layout our codec previously got
    // wrong (it would have dropped the private shares).
    let (payload, rest) = split_frame(vectors::SHARED_FILE_LIST_FRAME).unwrap().unwrap();
    assert!(rest.is_empty());

    let PeerMessage::SharedFileList(resp) = PeerMessage::decode(payload).unwrap() else {
        panic!("expected a shared file list");
    };

    assert_eq!(resp.directories.len(), 1);
    assert_eq!(resp.directories[0].path, "Music\\Album");
    assert_eq!(resp.directories[0].files[0].name, "Music\\Album\\song.mp3");
    assert_eq!(resp.directories[0].files[0].size, 5_242_880);

    assert_eq!(resp.private_directories.len(), 1, "private shares must be decoded");
    assert_eq!(resp.private_directories[0].path, "Buddies");
    assert_eq!(resp.private_directories[0].files[0].name, "Buddies\\secret.flac");
    assert_eq!(resp.private_directories[0].files[0].size, 999);
}

#[test]
fn user_info_response_body_matches_nicotine() {
    // Uncompressed body; our frame is [u32 len][u32 code][body], so strip 8.
    let frame = UserInfoResponse {
        description: "soulrust user".into(),
        picture: None,
        total_uploads: 42,
        queue_size: 3,
        slots_available: true,
        upload_allowed: 1,
    }
    .to_frame();
    assert_eq!(&frame[8..], vectors::USER_INFO_RESPONSE_BODY);
}

#[test]
fn folder_contents_request_body_matches_nicotine() {
    let frame = FolderContentsRequest { token: 1234, directory: "Music\\Album".into() }.to_frame();
    assert_eq!(&frame[8..], vectors::FOLDER_CONTENTS_REQUEST_BODY);
}

#[test]
fn our_decoder_accepts_nicotines_file_search_response() {
    // Nicotine+'s real zlib-compressed FileSearchResponse (peer code 9).
    let (payload, rest) = split_frame(vectors::FILE_SEARCH_RESPONSE_FRAME).unwrap().unwrap();
    assert!(rest.is_empty());

    let PeerMessage::FileSearchResponse(resp) = PeerMessage::decode(payload).unwrap() else {
        panic!("expected a file search response");
    };
    assert_eq!(resp.username, "peer");
    assert_eq!(resp.token, 0x2222);
    assert!(resp.free_slots);
    assert_eq!(resp.upload_speed, 5000);
    assert_eq!(resp.in_queue, 0);
    assert_eq!(resp.files.len(), 1);
    assert_eq!(resp.files[0].name, "Music\\hit.mp3");
    assert_eq!(resp.files[0].size, 4096);
    assert!(resp.private_files.is_empty());
}
