//! Cross-implementation conformance: our codec vs Nicotine+'s real output.
//!
//! The byte vectors in `fixtures/nicotine_vectors.rs` are generated by running
//! Nicotine+'s own message packers (see scripts/gen-nicotine-vectors.py). These
//! tests assert that our encoder produces the same bytes Nicotine+ does, and
//! that our decoder accepts Nicotine+'s real SharedFileListResponse — making the
//! reference implementation the executed oracle, not a human reading of it.

use std::net::Ipv4Addr;

use soulseek_proto::frame::split_frame;
use soulseek_proto::peer::{ConnectionType, PeerInit, PierceFirewall};
use soulseek_proto::peer_message::{
    FolderContentsRequest, GetSharedFileList, PeerMessage, UserInfoRequest, UserInfoResponse,
};
use soulseek_proto::server::{
    AcceptChildren, BranchLevel, BranchRoot, ConnectToPeerRequest, FileSearchRequest,
    GetPeerAddressRequest, HaveNoParent, LoginRequest, LoginResponse, ServerMessage, ServerRequest,
    SetWaitPort,
};
use soulseek_proto::distributed::{
    DistribBranchLevel, DistribBranchRoot, DistribChildDepth, DistribEmbedded, DistribPing,
    DistribSearch,
};
use soulseek_proto::transfer::{
    FileOffset, FileTransferInit, PlaceInQueueRequest, PlaceInQueueResponse, QueueUpload,
    TransferDirection, TransferRequest, TransferResponse, UploadDenied, UploadFailed,
};
use soulseek_proto::Reader;

mod vectors {
    include!("fixtures/nicotine_vectors.rs");
}

fn body<M: ServerRequest>(message: &M) -> Vec<u8> {
    let mut buf = Vec::new();
    message.encode_body(&mut buf);
    buf
}

#[test]
fn login_body_matches_nicotine() {
    let ours = body(&LoginRequest {
        username: "alice".into(),
        password: "s3cr3t".into(),
        major_version: 160,
        minor_version: 1,
    });
    // Includes the MD5(username+password) digest string — proves we compute it
    // the same way Nicotine+ does.
    assert_eq!(ours, vectors::LOGIN_BODY);
}

#[test]
fn get_peer_address_body_matches_nicotine() {
    let ours = body(&GetPeerAddressRequest { username: "alice".into() });
    assert_eq!(ours, vectors::GET_PEER_ADDRESS_BODY);
}

#[test]
fn file_search_body_matches_nicotine() {
    let ours = body(&FileSearchRequest { token: 0x1234_5678, query: "test query".into() });
    assert_eq!(ours, vectors::FILE_SEARCH_BODY);
}

#[test]
fn pierce_firewall_body_matches_nicotine() {
    // Peer-init frames are [u32 len][u8 code][body]; strip the 5-byte header.
    let frame = PierceFirewall { token: 4242 }.to_frame();
    assert_eq!(&frame[5..], vectors::PIERCE_FIREWALL_BODY);
}

#[test]
fn peer_init_body_matches_nicotine() {
    let frame = PeerInit {
        username: "alice".into(),
        connection_type: ConnectionType::Peer,
        token: 0,
    }
    .to_frame();
    assert_eq!(&frame[5..], vectors::PEER_INIT_BODY);
}

#[test]
fn shared_file_list_request_body_matches_nicotine() {
    // u32-code frames are [u32 len][u32 code][body]; the body is empty.
    let frame = GetSharedFileList.to_frame();
    assert_eq!(&frame[8..], vectors::SHARED_FILE_LIST_REQUEST_BODY);
}

#[test]
fn set_wait_port_is_a_soulseekqt_superset_of_nicotine() {
    // We send the SoulseekQt form: port + obfuscation_type + obfuscated_port.
    // Nicotine+ sends the port ALONE (slskmessages.py: `__slots__ = ("port",)`),
    // so the executed-oracle fixture SET_WAIT_PORT_BODY is just the 4-byte port.
    // The server accepts both; Nicotine+'s bytes must be the prefix of ours.
    let ours = body(&SetWaitPort { port: 2234, obfuscation_type: 0, obfuscated_port: 0 });
    assert_eq!(&ours[..vectors::SET_WAIT_PORT_BODY.len()], vectors::SET_WAIT_PORT_BODY);
    assert_eq!(ours.len(), 12, "port + obfuscation_type + obfuscated_port");
}

#[test]
fn our_decoder_accepts_nicotines_shared_file_list() {
    // Nicotine+'s real, compressed SharedFileListResponse with one public and
    // one private folder. Decoding it exercises the public dirs, the unknown=0
    // field, and the private-dir list — the layout our codec previously got
    // wrong (it would have dropped the private shares).
    let (payload, rest) = split_frame(vectors::SHARED_FILE_LIST_FRAME).unwrap().unwrap();
    assert!(rest.is_empty());

    let PeerMessage::SharedFileList(resp) = PeerMessage::decode(payload).unwrap() else {
        panic!("expected a shared file list");
    };

    assert_eq!(resp.directories.len(), 1);
    assert_eq!(resp.directories[0].path, "Music\\Album");
    assert_eq!(resp.directories[0].files[0].name, "Music\\Album\\song.mp3");
    assert_eq!(resp.directories[0].files[0].size, 5_242_880);

    assert_eq!(resp.private_directories.len(), 1, "private shares must be decoded");
    assert_eq!(resp.private_directories[0].path, "Buddies");
    assert_eq!(resp.private_directories[0].files[0].name, "Buddies\\secret.flac");
    assert_eq!(resp.private_directories[0].files[0].size, 999);
}

#[test]
fn user_info_response_body_matches_nicotine() {
    // Uncompressed body; our frame is [u32 len][u32 code][body], so strip 8.
    let frame = UserInfoResponse {
        description: "soulrust user".into(),
        picture: None,
        total_uploads: 42,
        queue_size: 3,
        slots_available: true,
        upload_allowed: 1,
    }
    .to_frame();
    assert_eq!(&frame[8..], vectors::USER_INFO_RESPONSE_BODY);
}

#[test]
fn user_info_response_with_picture_matches_nicotine() {
    // The pic-present path: our encoder must match Nicotine+'s has_pic=True body
    // (bool true, then the length-prefixed picture bytes), and our decoder must
    // read the picture back — neither direction is covered by the pic=None case.
    let response = UserInfoResponse {
        description: "soulrust user".into(),
        picture: Some(b"PNG!".to_vec()),
        total_uploads: 42,
        queue_size: 3,
        slots_available: true,
        upload_allowed: 1,
    };
    let frame = response.to_frame();
    assert_eq!(&frame[8..], vectors::USER_INFO_RESPONSE_WITH_PIC_BODY);

    let PeerMessage::UserInfoResponse(decoded) = PeerMessage::decode(&frame[4..]).unwrap() else {
        panic!("expected a user info response");
    };
    assert_eq!(decoded, response);
    assert_eq!(decoded.picture.as_deref(), Some(b"PNG!".as_slice()));
}

#[test]
fn connect_to_peer_request_body_matches_nicotine() {
    let frame = ConnectToPeerRequest {
        token: 0x0102_0304,
        username: "alice".into(),
        connection_type: ConnectionType::Peer,
    }
    .to_frame();
    assert_eq!(&frame[8..], vectors::CONNECT_TO_PEER_REQUEST_BODY);
}

#[test]
fn folder_contents_request_body_matches_nicotine() {
    let frame = FolderContentsRequest { token: 1234, directory: "Music\\Album".into() }.to_frame();
    assert_eq!(&frame[8..], vectors::FOLDER_CONTENTS_REQUEST_BODY);
}

#[test]
fn our_decoder_accepts_nicotines_file_search_response() {
    // Nicotine+'s real zlib-compressed FileSearchResponse (peer code 9).
    let (payload, rest) = split_frame(vectors::FILE_SEARCH_RESPONSE_FRAME).unwrap().unwrap();
    assert!(rest.is_empty());

    let PeerMessage::FileSearchResponse(resp) = PeerMessage::decode(payload).unwrap() else {
        panic!("expected a file search response");
    };
    assert_eq!(resp.username, "peer");
    assert_eq!(resp.token, 0x2222);
    assert!(resp.free_slots);
    assert_eq!(resp.upload_speed, 5000);
    assert_eq!(resp.in_queue, 0);
    assert_eq!(resp.files.len(), 1);
    assert_eq!(resp.files[0].name, "Music\\hit.mp3");
    assert_eq!(resp.files[0].size, 4096);
    assert!(resp.private_files.is_empty());
}

#[test]
fn our_decoder_accepts_nicotines_file_search_response_with_private_results() {
    // Nicotine+'s real compressed FileSearchResponse carrying BOTH a public and a
    // privately-shared file. Decoding it exercises the trailing private-results
    // branch (the unknown=0 field, then the private file list) — the same class
    // of conditional tail that once dropped private shares in SharedFileList.
    let (payload, rest) = split_frame(vectors::FILE_SEARCH_RESPONSE_PRIVATE_FRAME).unwrap().unwrap();
    assert!(rest.is_empty());

    let PeerMessage::FileSearchResponse(resp) = PeerMessage::decode(payload).unwrap() else {
        panic!("expected a file search response");
    };
    assert_eq!(resp.username, "peer");
    assert_eq!(resp.token, 0x2222);
    assert_eq!(resp.files.len(), 1);
    assert_eq!(resp.files[0].name, "Music\\hit.mp3");
    assert_eq!(resp.private_files.len(), 1, "private results must be decoded");
    assert_eq!(resp.private_files[0].name, "Buddies\\secret.flac");
    assert_eq!(resp.private_files[0].size, 999);
}

#[test]
fn user_info_request_body_matches_nicotine() {
    // UserInfoRequest has an empty body; our frame is [u32 len][u32 code].
    let frame = UserInfoRequest.to_frame();
    assert_eq!(&frame[8..], vectors::USER_INFO_REQUEST_BODY);
}

#[test]
fn our_decoder_accepts_nicotines_folder_contents_response() {
    // Nicotine+'s real FolderContentsResponse (peer code 37). Exercises the
    // token + requested dir + single folder layout with NO trailing field — the
    // divergence we just fixed (we used to emit an extra u32).
    let (payload, rest) = split_frame(vectors::FOLDER_CONTENTS_RESPONSE_FRAME).unwrap().unwrap();
    assert!(rest.is_empty());

    let PeerMessage::FolderContents(fc) = PeerMessage::decode(payload).unwrap() else {
        panic!("expected folder contents");
    };
    assert_eq!(fc.token, 1234);
    assert_eq!(fc.directory, "Music\\Album");
    assert_eq!(fc.folders.len(), 1);
    assert_eq!(fc.folders[0].path, "Music\\Album");
    assert_eq!(fc.folders[0].files[0].name, "song.mp3");
    assert_eq!(fc.folders[0].files[0].size, 5_242_880);
}

// --- Server->client / broadcast decode oracle ---------------------------------
// Bodies built by hand and validated by Nicotine+'s own parser (see
// scripts/gen-nicotine-vectors.py::decode_vectors). ServerMessage::decode takes
// a [u32 code][body] payload, so prepend the message code.

fn server_payload(code: u32, body: &[u8]) -> Vec<u8> {
    let mut payload = code.to_le_bytes().to_vec();
    payload.extend_from_slice(body);
    payload
}

#[test]
fn our_decoder_accepts_nicotines_get_peer_address_response() {
    let msg = ServerMessage::decode(&server_payload(3, vectors::GET_PEER_ADDRESS_RESPONSE_BODY))
        .unwrap();
    let ServerMessage::GetPeerAddress(resp) = msg else {
        panic!("expected a get-peer-address response");
    };
    assert_eq!(resp.username, "alice");
    assert_eq!(resp.ip, Ipv4Addr::new(198, 51, 100, 7));
    assert_eq!(resp.port, 2234);
    assert_eq!(resp.obfuscation_type, 0);
    assert_eq!(resp.obfuscated_port, 0);
}

#[test]
fn our_decoder_accepts_nicotines_connect_to_peer() {
    let msg = ServerMessage::decode(&server_payload(18, vectors::CONNECT_TO_PEER_BODY)).unwrap();
    let ServerMessage::ConnectToPeer(conn) = msg else {
        panic!("expected a connect-to-peer");
    };
    assert_eq!(conn.username, "bob");
    assert_eq!(conn.connection_type, ConnectionType::Peer);
    assert_eq!(conn.ip, Ipv4Addr::new(10, 0, 0, 5));
    assert_eq!(conn.port, 5000);
    assert_eq!(conn.token, 0x0102_0304);
    assert!(!conn.privileged);
}

#[test]
fn our_decoder_accepts_nicotines_login_success() {
    let msg = ServerMessage::decode(&server_payload(1, vectors::LOGIN_RESPONSE_SUCCESS_BODY))
        .unwrap();
    let ServerMessage::Login(LoginResponse::Success { greeting, own_ip, is_supporter, .. }) = msg
    else {
        panic!("expected a successful login");
    };
    assert_eq!(greeting, "Welcome to Soulseek!");
    assert_eq!(own_ip, Ipv4Addr::new(203, 0, 113, 9));
    assert!(is_supporter);
}

#[test]
fn our_decoder_accepts_nicotines_login_failure() {
    let msg = ServerMessage::decode(&server_payload(1, vectors::LOGIN_RESPONSE_FAILURE_BODY))
        .unwrap();
    let ServerMessage::Login(LoginResponse::Failure { reason, detail }) = msg else {
        panic!("expected a failed login");
    };
    assert_eq!(reason, "INVALIDPASS");
    assert_eq!(detail.as_deref(), Some("invalid password"));
}

#[test]
fn our_decoder_accepts_nicotines_file_search_broadcast() {
    let msg = ServerMessage::decode(&server_payload(26, vectors::FILE_SEARCH_BROADCAST_BODY))
        .unwrap();
    let ServerMessage::FileSearch(broadcast) = msg else {
        panic!("expected a file-search broadcast");
    };
    assert_eq!(broadcast.username, "searcher");
    assert_eq!(broadcast.token, 0xABCD);
    assert_eq!(broadcast.query, "deep purple");
}

#[test]
fn our_decoder_accepts_nicotines_excluded_search_phrases() {
    let msg = ServerMessage::decode(&server_payload(160, vectors::EXCLUDED_SEARCH_PHRASES_BODY))
        .unwrap();
    let ServerMessage::ExcludedSearchPhrases(excluded) = msg else {
        panic!("expected excluded search phrases");
    };
    assert_eq!(excluded.phrases, ["explicit", "banned phrase"]);
}

// --- file transfers -----------------------------------------------------------
// Peer-message transfer bodies; our frame is [u32 len][u32 code][body], so strip
// the 8-byte header to compare against Nicotine+'s make_network_message body.

#[test]
fn transfer_request_bodies_match_nicotine() {
    let upload = TransferRequest {
        direction: TransferDirection::Upload,
        token: 0xABCD,
        file: "Music\\song.mp3".into(),
        filesize: Some(5_242_880),
    }
    .to_frame();
    assert_eq!(&upload[8..], vectors::TRANSFER_REQUEST_UPLOAD_BODY);

    let download = TransferRequest {
        direction: TransferDirection::Download,
        token: 7,
        file: "x".into(),
        filesize: None,
    }
    .to_frame();
    assert_eq!(&download[8..], vectors::TRANSFER_REQUEST_DOWNLOAD_BODY);
}

#[test]
fn transfer_response_bodies_match_nicotine() {
    let allowed = TransferResponse { token: 9, allowed: true, filesize: Some(4096), reason: None }
        .to_frame();
    assert_eq!(&allowed[8..], vectors::TRANSFER_RESPONSE_ALLOWED_BODY);

    let rejected = TransferResponse {
        token: 9,
        allowed: false,
        filesize: None,
        reason: Some("Queued".into()),
    }
    .to_frame();
    assert_eq!(&rejected[8..], vectors::TRANSFER_RESPONSE_REJECTED_BODY);
}

#[test]
fn queue_and_place_in_queue_bodies_match_nicotine() {
    let queue = QueueUpload { file: "Music\\song.mp3".into() }.to_frame();
    assert_eq!(&queue[8..], vectors::QUEUE_UPLOAD_BODY);

    let request = PlaceInQueueRequest { file: "a\\b.mp3".into() }.to_frame();
    assert_eq!(&request[8..], vectors::PLACE_IN_QUEUE_REQUEST_BODY);

    let response = PlaceInQueueResponse { filename: "a\\b.mp3".into(), place: 3 }.to_frame();
    assert_eq!(&response[8..], vectors::PLACE_IN_QUEUE_RESPONSE_BODY);
}

#[test]
fn upload_denied_and_failed_bodies_match_nicotine() {
    let denied = UploadDenied { file: "a.mp3".into(), reason: "Not shared".into() }.to_frame();
    assert_eq!(&denied[8..], vectors::UPLOAD_DENIED_BODY);

    let failed = UploadFailed { file: "a.mp3".into() }.to_frame();
    assert_eq!(&failed[8..], vectors::UPLOAD_FAILED_BODY);
}

#[test]
fn f_connection_messages_match_nicotine() {
    // Raw bytes: no length prefix, no code — compare directly.
    assert_eq!(FileTransferInit { token: 0xABCD }.to_bytes(), vectors::FILE_TRANSFER_INIT_BYTES);
    assert_eq!(FileOffset { offset: 1_048_576 }.to_bytes(), vectors::FILE_OFFSET_BYTES);
}

// --- file transfers: decode direction -----------------------------------------
// The fixtures above come from Nicotine+'s real make_network_message(); here we
// feed those exact bytes BACK through our decoders, mirroring the
// `our_decoder_accepts_nicotines_*` tests for server/peer messages. PeerMessage
// transfer frames are [u32 code][body] once the length prefix is stripped, so
// prepend the peer code to each oracle body (codes from slskmessages.py).

fn peer_payload(code: u32, body: &[u8]) -> Vec<u8> {
    let mut payload = code.to_le_bytes().to_vec();
    payload.extend_from_slice(body);
    payload
}

#[test]
fn our_decoder_accepts_nicotines_transfer_request() {
    // Peer code 40. UPLOAD=1 carries the trailing u64 filesize; DOWNLOAD=0 does
    // not (slskmessages.py TransferRequest.parse_network_message reads filesize
    // only `if self.direction == TransferDirection.UPLOAD`).
    let PeerMessage::TransferRequest(upload) =
        PeerMessage::decode(&peer_payload(40, vectors::TRANSFER_REQUEST_UPLOAD_BODY)).unwrap()
    else {
        panic!("expected a transfer request");
    };
    assert_eq!(upload.direction, TransferDirection::Upload);
    assert_eq!(upload.token, 0xABCD);
    assert_eq!(upload.file, "Music\\song.mp3");
    assert_eq!(upload.filesize, Some(5_242_880));

    let PeerMessage::TransferRequest(download) =
        PeerMessage::decode(&peer_payload(40, vectors::TRANSFER_REQUEST_DOWNLOAD_BODY)).unwrap()
    else {
        panic!("expected a transfer request");
    };
    assert_eq!(download.direction, TransferDirection::Download);
    assert_eq!(download.token, 7);
    assert_eq!(download.file, "x");
    assert_eq!(download.filesize, None, "DOWNLOAD requests carry no filesize on the wire");
}

#[test]
fn our_decoder_accepts_nicotines_transfer_response() {
    // Peer code 41. Allowed => trailing u64 filesize; rejected => a reason string
    // (slskmessages.py TransferResponse.parse_network_message branches on
    // `allowed` after an early return when no content remains).
    let PeerMessage::TransferResponse(allowed) =
        PeerMessage::decode(&peer_payload(41, vectors::TRANSFER_RESPONSE_ALLOWED_BODY)).unwrap()
    else {
        panic!("expected a transfer response");
    };
    assert_eq!(allowed.token, 9);
    assert!(allowed.allowed);
    assert_eq!(allowed.filesize, Some(4096));
    assert_eq!(allowed.reason, None);

    let PeerMessage::TransferResponse(rejected) =
        PeerMessage::decode(&peer_payload(41, vectors::TRANSFER_RESPONSE_REJECTED_BODY)).unwrap()
    else {
        panic!("expected a transfer response");
    };
    assert_eq!(rejected.token, 9);
    assert!(!rejected.allowed);
    assert_eq!(rejected.filesize, None);
    assert_eq!(rejected.reason.as_deref(), Some("Queued"));

    // The real accept shape Nicotine+ actually sends (downloads.py builds
    // TransferResponse(allowed=True, token=...) with filesize unset): just
    // token + bool, so parse_network_message early-returns with no filesize.
    // Decoded straight from the body — there is no trailing content.
    let bare = TransferResponse::decode(&mut Reader::new(vectors::TRANSFER_RESPONSE_ACCEPTED_BARE_BODY))
        .unwrap();
    assert_eq!(bare, TransferResponse { token: 9, allowed: true, filesize: None, reason: None });
}

#[test]
fn our_decoder_accepts_nicotines_queue_and_place_in_queue() {
    // Peer codes 43 / 51 / 44.
    let PeerMessage::QueueUpload(queue) =
        PeerMessage::decode(&peer_payload(43, vectors::QUEUE_UPLOAD_BODY)).unwrap()
    else {
        panic!("expected a queue upload");
    };
    assert_eq!(queue.file, "Music\\song.mp3");

    let PeerMessage::PlaceInQueueRequest(request) =
        PeerMessage::decode(&peer_payload(51, vectors::PLACE_IN_QUEUE_REQUEST_BODY)).unwrap()
    else {
        panic!("expected a place-in-queue request");
    };
    assert_eq!(request.file, "a\\b.mp3");

    let PeerMessage::PlaceInQueueResponse(response) =
        PeerMessage::decode(&peer_payload(44, vectors::PLACE_IN_QUEUE_RESPONSE_BODY)).unwrap()
    else {
        panic!("expected a place-in-queue response");
    };
    assert_eq!(response.filename, "a\\b.mp3");
    assert_eq!(response.place, 3);
}

#[test]
fn our_decoder_accepts_nicotines_upload_denied_and_failed() {
    // Peer codes 50 / 46.
    let PeerMessage::UploadDenied(denied) =
        PeerMessage::decode(&peer_payload(50, vectors::UPLOAD_DENIED_BODY)).unwrap()
    else {
        panic!("expected an upload denied");
    };
    assert_eq!(denied.file, "a.mp3");
    assert_eq!(denied.reason, "Not shared");

    let PeerMessage::UploadFailed(failed) =
        PeerMessage::decode(&peer_payload(46, vectors::UPLOAD_FAILED_BODY)).unwrap()
    else {
        panic!("expected an upload failed");
    };
    assert_eq!(failed.file, "a.mp3");
}

#[test]
fn our_decoder_accepts_nicotines_f_connection_messages() {
    // Bare little-endian scalars, no frame: decode Nicotine+'s real
    // FileTransferInit (u32 token) and FileOffset (u64 offset) bytes directly.
    assert_eq!(FileTransferInit::decode(vectors::FILE_TRANSFER_INIT_BYTES).unwrap().token, 0xABCD);
    assert_eq!(FileOffset::decode(vectors::FILE_OFFSET_BYTES).unwrap().offset, 1_048_576);
}

// --- distributed (D-connection) messages -------------------------------------
// Encode bodies: our frame is [u32 len][u8 code][body], so strip 5 bytes.

#[test]
fn distributed_bodies_match_nicotine() {
    assert_eq!(&DistribPing.to_frame()[5..], vectors::DISTRIB_PING_BODY);
    assert_eq!(&DistribBranchLevel { level: 3 }.to_frame()[5..], vectors::DISTRIB_BRANCH_LEVEL_BODY);
    assert_eq!(
        &DistribBranchRoot { root_username: "alice".into() }.to_frame()[5..],
        vectors::DISTRIB_BRANCH_ROOT_BODY
    );
    assert_eq!(&DistribChildDepth { depth: 5 }.to_frame()[5..], vectors::DISTRIB_CHILD_DEPTH_BODY);
}

#[test]
fn our_decoder_accepts_nicotines_distrib_search() {
    let search = DistribSearch::decode(&mut Reader::new(vectors::DISTRIB_SEARCH_BODY)).unwrap();
    // Nicotine+ accepts the search only when chr(identifier) == "1", i.e.
    // the codepoint 49 (slskproto.py:749, 2381) — not the byte 1.
    assert_eq!(search.identifier, 49);
    assert_eq!(search.username, "bob");
    assert_eq!(search.token, 0xABCD);
    assert_eq!(search.query, "deep purple");
}

#[test]
fn our_decoder_accepts_nicotines_distrib_embedded() {
    let embedded = DistribEmbedded::decode(&mut Reader::new(vectors::DISTRIB_EMBEDDED_BODY)).unwrap();
    assert_eq!(embedded.inner_code, 3, "inner message is a DistribSearch");
    // The inner bytes are exactly the DistribSearch body, and decode back.
    assert_eq!(embedded.inner_message, vectors::DISTRIB_SEARCH_BODY);
    let inner = DistribSearch::decode(&mut Reader::new(&embedded.inner_message)).unwrap();
    assert_eq!(inner.query, "deep purple");
}

// --- server distributed/parent-management messages ---------------------------

#[test]
fn branch_level_and_root_bodies_match_nicotine() {
    assert_eq!(&BranchLevel { level: 3 }.to_frame()[8..], vectors::BRANCH_LEVEL_BODY);
    assert_eq!(&BranchRoot { root: "alice".into() }.to_frame()[8..], vectors::BRANCH_ROOT_BODY);
}

#[test]
fn have_no_parent_and_accept_children_bodies_match_nicotine() {
    assert_eq!(&HaveNoParent { no_parent: true }.to_frame()[8..], vectors::HAVE_NO_PARENT_BODY);
    assert_eq!(&AcceptChildren { accept: false }.to_frame()[8..], vectors::ACCEPT_CHILDREN_BODY);
}

#[test]
fn our_decoder_accepts_nicotines_parent_management_messages() {
    let msg = ServerMessage::decode(&server_payload(83, vectors::PARENT_MIN_SPEED_BODY)).unwrap();
    let ServerMessage::ParentMinSpeed(p) = msg else { panic!("expected parent min speed") };
    assert_eq!(p.speed, 1500);

    let msg = ServerMessage::decode(&server_payload(84, vectors::PARENT_SPEED_RATIO_BODY)).unwrap();
    let ServerMessage::ParentSpeedRatio(p) = msg else { panic!("expected parent speed ratio") };
    assert_eq!(p.ratio, 50);

    let msg = ServerMessage::decode(&server_payload(102, vectors::POSSIBLE_PARENTS_BODY)).unwrap();
    let ServerMessage::PossibleParents(pp) = msg else { panic!("expected possible parents") };
    assert_eq!(pp.parents.len(), 1);
    assert_eq!(pp.parents[0].username, "parent1");
    assert_eq!(pp.parents[0].ip, Ipv4Addr::new(10, 0, 0, 1));
    assert_eq!(pp.parents[0].port, 2234);
}

#[test]
fn our_decoder_accepts_nicotines_embedded_message() {
    let msg = ServerMessage::decode(&server_payload(93, vectors::EMBEDDED_MESSAGE_BODY)).unwrap();
    let ServerMessage::EmbeddedMessage(em) = msg else { panic!("expected embedded message") };
    assert_eq!(em.distrib_code, 3, "wraps a DistribSearch");
    // The inner bytes decode back to a DistribSearch.
    let inner = DistribSearch::decode(&mut Reader::new(&em.distrib_message)).unwrap();
    assert_eq!(inner.query, "deep purple");
}
