//! Code generation — the equivalent of `templates.go` + `generator.go` in the
//! Go tools, using `quote!` instead of `text/template`.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Ident, Type};

use crate::spec::{Component, MessageDef, Spec};

/// `controller_pool` -> `ControllerPool`.
fn pascal(name: &Ident) -> String {
    name.to_string()
        .split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// `GetTenantHTTPRequest` -> `get_tenant_http_request`.
fn camel_to_snake(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() {
            let prev_is_lower = i > 0 && (chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit());
            let next_is_lower = i + 1 < chars.len() && chars[i + 1].is_lowercase();
            if i > 0 && (prev_is_lower || (chars[i - 1].is_uppercase() && next_is_lower)) {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

/// Method-name suffix for a message type: the last path segment with a
/// trailing `Proto` stripped, snake-cased. The equivalent of the Go
/// `baseName` template function (`*controllerpb.GetTenantRequest` ->
/// `GetTenantRequest`), e.g. `pb::TenantUpdatedProto` -> `tenant_updated`.
fn method_suffix(ty: &Type) -> syn::Result<String> {
    let Type::Path(path) = ty else {
        return Err(syn::Error::new_spanned(
            ty,
            "message type must be a (possibly qualified) type path",
        ));
    };
    let segment = path
        .path
        .segments
        .last()
        .ok_or_else(|| syn::Error::new_spanned(ty, "message type path is empty"))?;
    let name = segment.ident.to_string();
    let name = name.strip_suffix("Proto").unwrap_or(&name);
    Ok(camel_to_snake(name))
}

fn send_method(msg: &MessageDef) -> syn::Result<Ident> {
    Ok(format_ident!("send_{}", method_suffix(&msg.message)?))
}

fn handle_method(msg: &MessageDef) -> syn::Result<Ident> {
    Ok(format_ident!("handle_{}", method_suffix(&msg.message)?))
}

/// One generated identifier bundle per component.
struct Names {
    sendable_trait: Ident,
    handler_trait: Ident,
    view_struct: Ident,
    view_method: Ident,
    /// Generic parameter on the messenger (handler components only).
    /// `T`-prefixed so it cannot shadow a message type of the same name.
    type_param: Ident,
    field: Ident,
}

impl Names {
    fn new(component: &Component) -> Self {
        let pascal = pascal(&component.name);
        Names {
            sendable_trait: format_ident!("{pascal}Sendable"),
            handler_trait: format_ident!("{pascal}Handler"),
            view_struct: format_ident!("{pascal}SendableView"),
            view_method: format_ident!("{}_sendable", component.name),
            type_param: format_ident!("T{pascal}"),
            field: component.name.clone(),
        }
    }
}

pub fn generate(spec: &Spec) -> syn::Result<TokenStream> {
    let names: Vec<Names> = spec.components.iter().map(Names::new).collect();
    let messenger = &spec.messenger_name;

    // Only components that handle messages are stored in the messenger,
    // each as a generic parameter bound by its handler trait.
    let handler_idx: Vec<usize> = (0..spec.components.len())
        .filter(|&i| !spec.components[i].handles.is_empty())
        .collect();
    let params: Vec<&Ident> = handler_idx.iter().map(|&i| &names[i].type_param).collect();
    let bounds: Vec<TokenStream> = handler_idx
        .iter()
        .map(|&i| {
            let param = &names[i].type_param;
            let handler_trait = &names[i].handler_trait;
            quote!(#param: #handler_trait)
        })
        .collect();
    let fields: Vec<&Ident> = handler_idx.iter().map(|&i| &names[i].field).collect();
    let field_params: Vec<&Ident> = params.clone();

    let mut items = TokenStream::new();

    // Sendable and Handler traits (the interface-gen-v2 output).
    for (component, n) in spec.components.iter().zip(&names) {
        if !component.sends.is_empty() {
            let sendable_trait = &n.sendable_trait;
            let doc = format!(
                "Messages that `{}` can send. Generated by `messenger!`.",
                component.name
            );
            let methods = component
                .sends
                .iter()
                .map(|msg| {
                    let method = send_method(msg)?;
                    let message = &msg.message;
                    Ok(match &msg.response {
                        Some(response) => quote!(fn #method(&mut self, msg: #message) -> #response;),
                        None => quote!(fn #method(&mut self, msg: #message);),
                    })
                })
                .collect::<syn::Result<Vec<_>>>()?;
            items.extend(quote! {
                #[doc = #doc]
                pub trait #sendable_trait {
                    #(#methods)*
                }
            });
        }

        if !component.handles.is_empty() {
            let handler_trait = &n.handler_trait;
            let doc = format!(
                "Handler methods that `{}` must implement. Generated by `messenger!`.",
                component.name
            );
            let methods = component
                .handles
                .iter()
                .map(|msg| {
                    let method = handle_method(msg)?;
                    let message = &msg.message;
                    Ok(match &msg.response {
                        Some(response) => quote!(fn #method(&mut self, msg: #message) -> #response;),
                        None => quote!(fn #method(&mut self, msg: #message);),
                    })
                })
                .collect::<syn::Result<Vec<_>>>()?;
            items.extend(quote! {
                #[doc = #doc]
                pub trait #handler_trait {
                    #(#methods)*
                }
            });
        }
    }

    // The messenger struct (the messenger-gen-v2 output): owns every handling
    // component and routes sends to handles.
    let messenger_doc = format!("Generated message router `{messenger}`.");
    items.extend(quote! {
        #[doc = #messenger_doc]
        pub struct #messenger<#(#params,)*> {
            #(pub #fields: #field_params,)*
        }
    });

    // Per-sending-component view structs and their `<name>_sendable()`
    // accessors — the Rust equivalent of the Go `SetSendable` wiring.
    let mut view_methods = TokenStream::new();
    for (component, n) in spec.components.iter().zip(&names) {
        if component.sends.is_empty() {
            continue;
        }
        let view_struct = &n.view_struct;
        let view_method = &n.view_method;
        let view_doc = format!(
            "Routes messages sent by `{}`. Obtain via `{messenger}::{view_method}`.",
            component.name
        );

        let routes = component
            .sends
            .iter()
            .map(|msg| {
                let method = send_method(msg)?;
                let handle = handle_method(msg)?;
                let message = &msg.message;
                let handlers = spec.handlers_for(&msg.key());

                Ok(if let Some(response) = &msg.response {
                    // 1:1 — validation guarantees exactly one handler.
                    let field = &handlers[0].name;
                    quote! {
                        fn #method(&mut self, msg: #message) -> #response {
                            self.parent.#field.#handle(msg)
                        }
                    }
                } else if handlers.is_empty() {
                    quote! {
                        fn #method(&mut self, msg: #message) {
                            let _ = msg;
                        }
                    }
                } else {
                    // Event fan-out: clone for every handler but the last.
                    let (last, rest) = handlers.split_last().expect("non-empty");
                    let rest_fields = rest.iter().map(|h| &h.name);
                    let last_field = &last.name;
                    quote! {
                        fn #method(&mut self, msg: #message) {
                            #(self.parent.#rest_fields.#handle(msg.clone());)*
                            self.parent.#last_field.#handle(msg);
                        }
                    }
                })
            })
            .collect::<syn::Result<Vec<_>>>()?;

        let sendable_trait = &n.sendable_trait;
        items.extend(quote! {
            #[doc = #view_doc]
            pub struct #view_struct<'a, #(#params,)*> {
                parent: &'a mut #messenger<#(#params,)*>,
            }

            impl<'a, #(#bounds,)*> #sendable_trait for #view_struct<'a, #(#params,)*> {
                #(#routes)*
            }
        });

        let accessor_doc = format!("Returns the sendable view for `{}`.", component.name);
        view_methods.extend(quote! {
            #[doc = #accessor_doc]
            pub fn #view_method(&mut self) -> #view_struct<'_, #(#params,)*> {
                #view_struct { parent: self }
            }
        });
    }

    items.extend(quote! {
        impl<#(#bounds,)*> #messenger<#(#params,)*> {
            /// Creates a new messenger owning all handling components.
            pub fn new(#(#fields: #field_params,)*) -> Self {
                Self { #(#fields,)* }
            }

            #view_methods
        }
    });

    Ok(items)
}
